Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -835,6 +835,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --disable-msvc          don't require MS Visual C++ on Cygwin
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-maintainer-mode enable make rules and dependencies not useful
@@ -1244,41 +1245,70 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 # If the Microsoft Visual C++ cl.exe compiler is available, set us up for
 # compiling with it.
 
-# **************************************************************************
-# If the Microsoft Visual C++ cl.exe compiler is available, set us up for
-# compiling with it and to generate an MSWindows .dll file.
 
-: ${BUILD_WITH_MSVC=false}
-sim_ac_wrapmsvc=`cd $srcdir; pwd`/cfg/wrapmsvc.exe
-if test -z "$CC" -a -z "$CXX" && $sim_ac_wrapmsvc >/dev/null 2>&1; then
+# Check whether --enable-msvc or --disable-msvc was given.
+if test "${enable_msvc+set}" = set; then
+  enableval="$enable_msvc"
+  case $enableval in
+  no | false) sim_ac_try_msvc=false ;;
+  *)          sim_ac_try_msvc=true ;;
+  esac
+else
+  sim_ac_try_msvc=true
+fi;
 
 
-  CC=$sim_ac_wrapmsvc
-  CXX=$sim_ac_wrapmsvc
-  export CC CXX
-  BUILD_WITH_MSVC=true
+
+
+BUILD_WITH_MSVC=false
+if $sim_ac_try_msvc; then
+  sim_ac_wrapmsvc=`cd $srcdir; pwd`/cfg/wrapmsvc.exe
+  if test -z "$CC" -a -z "$CXX" && $sim_ac_wrapmsvc >/dev/null 2>&1; then
+
+
+    CC=$sim_ac_wrapmsvc
+    CXX=$sim_ac_wrapmsvc
+    export CC CXX
+    BUILD_WITH_MSVC=true
+  else
+    case $host in
+    *-cygwin)
+echo >&2 ""
+
+
+: ${sim_ac_message_file=$ac_aux_dir/errors.txt}
+if test -f $sim_ac_message_file; then
+  sim_ac_message="`sed -n -e '/^!no-msvc++$/,/^!/ { /^!/ d; p; }' <$sim_ac_message_file`"
+  if test x"$sim_ac_message" = x""; then
+    { { echo "$as_me:$LINENO: error: no message named 'no-msvc++' in '$sim_ac_message_file' - notify the $PACKAGE_NAME maintainer(s)" >&5
+echo "$as_me: error: no message named 'no-msvc++' in '$sim_ac_message_file' - notify the $PACKAGE_NAME maintainer(s)" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    eval "echo >&2 \"$sim_ac_message\""
+  fi
+else
+  { { echo "$as_me:$LINENO: error: file '$sim_ac_message_file' not found - notify the $PACKAGE_NAME maintainer(s)" >&5
+echo "$as_me: error: file '$sim_ac_message_file' not found - notify the $PACKAGE_NAME maintainer(s)" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
-case $CXX in
-*wrapmsvc.exe)
-  BUILD_WITH_MSVC=true
 
-
-  ;;
-*)
-  BUILD_WITH_MSVC=false
-
-  case $host in
-  *-cygwin)
-    { { echo "$as_me:$LINENO: error: You need Microsoft Visual C++ to build on Cygwin" >&5
-echo "$as_me: error: You need Microsoft Visual C++ to build on Cygwin" >&2;}
+echo >&2 ""
+{ { echo "$as_me:$LINENO: error: aborting" >&5
+echo "$as_me: error: aborting" >&2;}
    { (exit 1); exit 1; }; }
-    ;;
-  esac
+ ;;
+    esac
+  fi
+fi
 
-  ;;
-esac
+
+if $BUILD_WITH_MSVC; then
+  :
+else
+  :
+fi
 
 
 # *******************************************************************
@@ -3007,7 +3037,6 @@ if test x"$with_dl" != xno; then
     sim_ac_dl_cppflags="-I${with_dl}/include"
     sim_ac_dl_ldflags="-L${with_dl}/lib"
   fi
-  sim_ac_dl_libs="-ldl"
 
   sim_ac_save_cppflags=$CPPFLAGS
   sim_ac_save_ldflags=$LDFLAGS
@@ -3015,7 +3044,6 @@ if test x"$with_dl" != xno; then
 
   CPPFLAGS="$CPPFLAGS $sim_ac_dl_cppflags"
   LDFLAGS="$LDFLAGS $sim_ac_dl_ldflags"
-  LIBS="$sim_ac_dl_libs $LIBS"
 
   # Use SIM_AC_CHECK_HEADERS instead of .._HEADER to get the
   # HAVE_DLFCN_H symbol set up in config.h automatically.
@@ -3134,12 +3162,16 @@ fi
 done
 
 
-  echo "$as_me:$LINENO: checking whether the dynamic link loader library is available" >&5
-echo $ECHO_N "checking whether the dynamic link loader library is available... $ECHO_C" >&6
-if test "${sim_cv_lib_dl_avail+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
+  sim_ac_dl_avail=false
+
+  echo "$as_me:$LINENO: checking for the dl library" >&5
+echo $ECHO_N "checking for the dl library... $ECHO_C" >&6
+  # At least under FreeBSD, dlopen() et al is part of the C library.
+  # On HP-UX, dlopen() might reside in a library "svld" instead of "dl".
+  for sim_ac_dl_libcheck in "" "-ldl" "-lsvld"; do
+    if ! $sim_ac_dl_avail; then
+      LIBS="$sim_ac_dl_libcheck $sim_ac_save_libs"
+      cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -3173,18 +3205,31 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_cv_lib_dl_avail=yes
+  sim_ac_dl_avail=true
+                   sim_ac_dl_libs="$sim_ac_dl_libcheck"
+
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-sim_cv_lib_dl_avail=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: $sim_cv_lib_dl_avail" >&5
-echo "${ECHO_T}$sim_cv_lib_dl_avail" >&6
+    fi
+  done
 
-  if test x"$sim_cv_lib_dl_avail" = xyes; then
+  if $sim_ac_dl_avail; then
+    if test x"$sim_ac_dl_libs" = x""; then
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    else
+      echo "$as_me:$LINENO: result: $sim_ac_dl_cppflags $sim_ac_dl_ldflags $sim_ac_dl_libs" >&5
+echo "${ECHO_T}$sim_ac_dl_cppflags $sim_ac_dl_ldflags $sim_ac_dl_libs" >&6
+    fi
+  else
+    echo "$as_me:$LINENO: result: not available" >&5
+echo "${ECHO_T}not available" >&6
+  fi
+
+  if $sim_ac_dl_avail; then
     :
   else
     CPPFLAGS=$sim_ac_save_cppflags
@@ -4208,8 +4253,18 @@ if test x"$with_pthread" != xno; then
     sim_ac_pthread_cppflags="-I${with_pthread}/include"
     sim_ac_pthread_ldflags="-L${with_pthread}/lib"
   fi
+
+  # FIXME: should investigate and document the exact meaning of
+  # the _REENTRANT flag. larsa's commit message mentions
+  # "glibc-doc/FAQ.threads.html". Also, kintel points to the
+  # comp.programming.thrads FAQ, which has an entry on the
+  # _REENTRANT define.
+  #
+  # Preferably, it should only be set up when really needed
+  # (as detected by some other configure check).
+  #
+  # 20030306 mortene.
   sim_ac_pthread_cppflags="-D_REENTRANT ${sim_ac_pthread_cppflags}"
-  sim_ac_pthread_libs="-lpthread"
 
   sim_ac_save_cppflags=$CPPFLAGS
   sim_ac_save_ldflags=$LDFLAGS
@@ -4217,14 +4272,16 @@ if test x"$with_pthread" != xno; then
 
   CPPFLAGS="$CPPFLAGS $sim_ac_pthread_cppflags"
   LDFLAGS="$LDFLAGS $sim_ac_pthread_ldflags"
-  LIBS="$sim_ac_pthread_libs $LIBS"
+
+  sim_ac_pthread_avail=false
 
   echo "$as_me:$LINENO: checking for POSIX threads" >&5
 echo $ECHO_N "checking for POSIX threads... $ECHO_C" >&6
-if test "${sim_cv_lib_pthread_avail+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
+  # At least under FreeBSD, we link to pthreads library with -pthread.
+  for sim_ac_pthreads_libcheck in "-lpthread" "-pthread"; do
+    if ! $sim_ac_pthread_avail; then
+      LIBS="$sim_ac_pthreads_libcheck $sim_ac_save_libs"
+      cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 #include <pthread.h>
@@ -4254,18 +4311,26 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  sim_cv_lib_pthread_avail=true
+  sim_ac_pthread_avail=true
+                   sim_ac_pthread_libs="$sim_ac_pthreads_libcheck"
+
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-sim_cv_lib_pthread_avail=false
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: $sim_cv_lib_pthread_avail" >&5
-echo "${ECHO_T}$sim_cv_lib_pthread_avail" >&6
+    fi
+  done
 
-  if $sim_cv_lib_pthread_avail; then
+  if $sim_ac_pthread_avail; then
+    echo "$as_me:$LINENO: result: $sim_ac_pthread_cppflags $sim_ac_pthread_ldflags $sim_ac_pthread_libs" >&5
+echo "${ECHO_T}$sim_ac_pthread_cppflags $sim_ac_pthread_ldflags $sim_ac_pthread_libs" >&6
+  else
+    echo "$as_me:$LINENO: result: not available" >&5
+echo "${ECHO_T}not available" >&6
+  fi
+
+  if $sim_ac_pthread_avail; then
     echo "$as_me:$LINENO: checking the struct timespec resolution" >&5
 echo $ECHO_N "checking the struct timespec resolution... $ECHO_C" >&6
 if test "${sim_cv_lib_pthread_timespec_resolution+set}" = set; then
@@ -4321,8 +4386,7 @@ _ACEOF
     fi
   fi
 
-  if $sim_cv_lib_pthread_avail; then
-    sim_ac_pthread_avail=yes
+  if $sim_ac_pthread_avail; then
 
           sim_ac_ogl_cppflags="$sim_ac_ogl_cppflags $sim_ac_pthread_cppflags"
           sim_ac_ogl_ldflags="$sim_ac_ogl_ldflags $sim_ac_pthread_ldflags"
@@ -4489,7 +4553,7 @@ else
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
-#include <OpenGL/gl.h>
+#include <OpenGL/glu.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -4508,14 +4572,14 @@ else
   ac_cpp_err=yes
 fi
 if test -z "$ac_cpp_err"; then
-  ac_cv_header_OpenGL_gl_h=yes
+  ac_cv_header_OpenGL_glu_h=yes
 else
   echo "$as_me: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  ac_cv_header_OpenGL_gl_h=no
+  ac_cv_header_OpenGL_glu_h=no
 fi
 rm -f conftest.err conftest.$ac_ext
-if test $ac_cv_header_OpenGL_gl_h = yes; then
+if test $ac_cv_header_OpenGL_glu_h = yes; then
 
       sim_ac_glu_header_avail=true
       sim_ac_glu_header=OpenGL/glu.h
@@ -5143,10 +5207,14 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-  if $sim_ac_coin_configcmd; then
+
+  if ! test "X$sim_ac_coin_configcmd" = "Xfalse"; then
     test -n "$CONFIG" &&
       $sim_ac_coin_configcmd --alternate=$CONFIG >/dev/null 2>/dev/null &&
       sim_ac_coin_configcmd="$sim_ac_coin_configcmd --alternate=$CONFIG"
+  fi
+
+  if $sim_ac_coin_configcmd; then
     sim_ac_coin_version=`$sim_ac_coin_configcmd --version`
     sim_ac_coin_cppflags=`$sim_ac_coin_configcmd --cppflags`
     sim_ac_coin_cflags=`$sim_ac_coin_configcmd --cflags 2>/dev/null`
@@ -5254,7 +5322,7 @@ fi
 # ** Generate output files.
 # *******************************************************************
 
-ac_config_files="$ac_config_files Makefile ivNodeKitStructure/Makefile ivcat/Makefile ivfix/Makefile ivhierarchy/Makefile renderos/Makefile"
+ac_config_files="$ac_config_files Makefile ivNodeKitStructure/Makefile ivcat/Makefile ivfix/Makefile ivhierarchy/Makefile ivperf/Makefile renderos/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -5742,6 +5810,7 @@ do
   "ivcat/Makefile" ) CONFIG_FILES="$CONFIG_FILES ivcat/Makefile" ;;
   "ivfix/Makefile" ) CONFIG_FILES="$CONFIG_FILES ivfix/Makefile" ;;
   "ivhierarchy/Makefile" ) CONFIG_FILES="$CONFIG_FILES ivhierarchy/Makefile" ;;
+  "ivperf/Makefile" ) CONFIG_FILES="$CONFIG_FILES ivperf/Makefile" ;;
   "renderos/Makefile" ) CONFIG_FILES="$CONFIG_FILES renderos/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
